DROP DATABASE IF EXISTS empTrackerDB;

CREATE DATABASE empTrackerDB;

CREATE TABLE department (
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(30) NOT NULL,
    PRIMARY KEY(id)
)

CREATE TABLE role (
    id INT AUTO_INCRIMENT NOT NULL,
    title VARCHAR(30) NULL,
    salary DECIMAL(10,2) NULL,
    department_id 
    PRIMARY KEY(id)
)